# Generated by Django 4.2.7 on 2025-06-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
