# Generated by Django 4.2.7 on 2025-05-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
