services:
  - type: web
    name: edumanage-drf-server
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
    startCommand: python manage.py runserver 0.0.0.0:80
