services:
  - type: web
    name: edumanage-drf-server
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python manage.py migrate users zero --noinput
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      gunicorn edumanage-drf-server.wsgi:application --bind 0.0.0.0:$PORT