# Generated by Django 5.2.1 on 2025-05-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='description',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='myclass',
            old_name='description',
            new_name='short_description',
        ),
        migrations.RemoveField(
            model_name='class',
            name='assignments_count',
        ),
        migrations.RemoveField(
            model_name='class',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='class',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='myclass',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='myclass',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='class',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='myclass',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='class',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
        migrations.AlterField(
            model_name='myclass',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
    ]
