# Generated by Django 4.2.7 on 2025-05-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_myclass_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
