# Generated by Django 4.2.7 on 2025-06-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_myclass_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='assignment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
