# Generated by Django 4.2.7 on 2025-06-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
