# Generated by Django 4.2.7 on 2025-06-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_assignment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_count',
        ),
    ]
